Neos:
  GoogleAnalytics:
    sites:
      # All site specific settings are indexed by site node name
      site:
        analytics:
          id: "UA-XXXXX-YY"
        # tagManager:
        #   id: 'GTM-XXXXX'
