Neos:
  Neos:
    nodeTypes:
      presets:
        properties:
          'text':
            'title':
              type: string
              defaultValue: ''
              ui:
                inlineEditable: true
                inline:
                  editorOptions:
                    placeholder: 'Enter headline here...'
                    hyphens: true
                    nbsp: true
                    formatting:
                      h1: false
                      h2: true
                      h3: true
                      h4: true
                      h5: true
                      a: true
                      sub: true
                      sup: true
            'plain':
              type: string
              defaultValue: ''
              ui:
                inlineEditable: true
                inline:
                  editorOptions:
                    placeholder: 'Enter headline here...'
                    autoparagraph: false
                    hyphens: true
                    nbsp: true
                    formatting:
                      sub: true
                      sup: true
            'plainWithStrong':
              type: string
              defaultValue: ''
              ui:
                inlineEditable: true
                inline:
                  editorOptions:
                    placeholder: 'Enter headline here...'
                    autoparagraph: false
                    hyphens: true
                    nbsp: true
                    formatting:
                      strong: true
                      sub: true
                      sup: true
            'free':
              type: string
              defaultValue: ''
              ui:
                inlineEditable: true
                inline:
                  editorOptions:
                    placeholder: 'Enter text here...'
                    autoparagraph: true
                    hyphens: true
                    nbsp: true
                    formatting:
                      strong: true
                      sub: true
                      sup: true
                      p: true
                      h1: false
                      h2: true
                      h3: true
                      h4: true
                      h5: true
                      h6: false
                      pre: false
                      table: true
                      ol: true
                      ul: true
                      a: true
            'link':
              type: string
              ui:
                label: 'Link'
                reloadPageIfChanged: false
                inspector:
                  group: general
                  editor: 'Neos.Neos/Inspector/Editors/LinkEditor'
          'image':
            'asset':
              type: Neos\Media\Domain\Model\ImageInterface
              ui:
                label: 'Image'
                reloadIfChanged: true
                inspector:
                  group: general
                  position: 50
            'assets':
              type: array<Neos\Media\Domain\Model\Asset>
              ui:
                label: 'Images'
                editor: Neos.Neos/Inspector/Editors/AssetEditor
                editorOptions:
                  multiple: true
                  features:
                    upload: true
                    mediaBrowser: true
                reloadIfChanged: true
                inspector:
                  group: general
                  position: 50
            'squareAsset':
              type: Neos\Media\Domain\Model\ImageInterface
              ui:
                label: 'Image'
                reloadIfChanged: true
                inspector:
                  group: general
                  position: 50
                  editorOptions:
                    crop:
                      aspectRatio:
                        enableOriginal: false
                        allowCustom: false
                        locked:
                          width: 1
                          height: 1
            'alternativeText':
              type: string
              ui:
                label: 'Alternative image text'
                help:
                  message: 'This text is used for accessibility and for search engine optimization.'
                reloadIfChanged: false
                inspector:
                  group: general
                  position: 100
          'date':
            'createdAt':
              type: DateTime
              defaultValue: now
              ui:
                label: 'Publication date'
                reloadIfChanged: true
                inspector:
                  group: document
                  position: 'after uriPathSegment'
                  editorOptions:
                    format: 'd.m.Y'
              validation:
                Neos.Neos/Validation/NotEmptyValidator: {  }
                Neos.Neos/Validation/DateTimeValidator: {  }
