
Neos:
  Flow:
    i18n:
      defaultLocale: en
  ContentRepository:
    contentDimensions:
      language:
        label: Languages
        icon: icon-language
        # The default dimension that is applied when creating nodes without specifying a dimension
        default: en
        # The default preset to use if no URI segment was given when resolving languages in the router
        defaultPreset: en
        presets:
          # de:
          #   label: Deutsch
          #   values:
          #     - de
          #   uriSegment: 'de'
          en:
            label: English
            values:
              - en
            uriSegment: ''
  Neos:
    userInterface:
      defaultLanguage: en
      translation:
        autoInclude:
          CodeQ.Site:
            - Main
            - 'NodeTypes/*'
