
Carbon:
  IncludeAssets:
    Packages:
      aa_Theme:
        Path:
          Inline:
            CSS: 'Public/Frontend'
            JS: 'Public/Frontend'
          File:
            CSS: 'Public/Frontend'
            JS: 'Public/Frontend'
        # Asset files who get's loaded in live and backend view
        General:
          Head:
            - index.css
          Body:
            - index.js

      ##
      # Sitegeist.Lazybones required lazysizes, we recommend to include lazysizes javascript
      # from https://github.com/aFarkas/lazysizes into your own fe-build and remove this section
      ##
      'bb_Sitegeist.Lazybones':
        Package: 'Sitegeist.Lazybones'
        Path:
          File:
            JS: 'Public/JavaScript'
        General:
          Body:
            - lazysizes.min.js
