##
# Enforces our best practise Coding Conventions
# 
# Composer require - backgground info:
# We want this configuration inside the site package. So the 
# single-repo setup requires that the package is a normal
# dependency.
##
Sitegeist:
  NeosGuidelines:
    distribution:
      validators:
        MandatoryFiles:
          options:
            files: ['README.md', 'composer.json', '.editorconfig']
        ReadmeSections:
          options:
            requiredSections:
              - 'Hosting'
              - false
              - false
              - false
        Composer:
          options:
            requiredSettings: {}
    packages:
      # the list of the packages that should be validated
      packageKeys: ['CodeQ.Site']
      validators:
        MandatoryFiles:
          options:
            files: ['composer.json', 'Resources/Public/Frontend/Readme.md']
        Fusion:
          options:
            excludedFileNames: ['Root.fusion', 'Shame.fusion', 'Override.fusion']
