
Neos:
  Flow:
    mvc:
      routes:
        'Neos.Neos':
          variables:
            # We prefer URLs without the ".html" suffix
            defaultUriSuffix: ''
    error:
      exceptionHandler:
        renderingGroups:
          notFoundExceptions:
            options:
              variables:
                path: '404' # skip suffix in notfound as well
  Neos:
    eventLog:
      enabled: true
    userInterface:
      navigateComponent:
        nodeTree:
          loadingDepth: 1
        structureTree:
          loadingDepth: 2
    fusion:
      autoInclude:
        CodeQ.Site: true
    # nodeTypes:
    #   groups:
    #     contentBlocks:
    #       position: 110
    #       label: 'Content Blocks'
    Ui:
      frontendConfiguration:
        defaultInlineEditor: 'ckeditor5'
        hotkeys: ~
