#                                                                        #
# Routes configuration                                                   #
#                                                                        #
# This file contains the configuration for the MVC router.               #
# Just add your own modifications as necessary.                          #
#                                                                        #
# Please refer to the Flow manual for possible configuration options.    #
#                                                                        #

##
# Neos Seo: XML Sitemap

-
  name: 'Neos Seo'
  uriPattern: '<TYPO3NeosSeoSubroutes>'
  subRoutes:
        'TYPO3NeosSeoSubroutes':
          package: 'TYPO3.Neos.Seo'
          variables:
                'xmlSitemapPath': 'sitemap.xml'

##
# Neos subroutes

-
  name: 'TYPO3Neos'
  uriPattern: '<TYPO3NeosSubroutes>'
  subRoutes:
    'TYPO3NeosSubroutes':
      package: 'TYPO3.Neos'
      variables:
        'defaultUriSuffix': '.html'
